name: IoT Infrastructure CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Validate SAM template
        run: sam validate --template-file template.yaml --lint

      - name: Build SAM application
        run: sam build --template-file template.yaml
